//
// Pauli Spinor Algebra Package
//
// The present package implements all the basic algorithms dealing
// with Pauli spinors, which form a fundamental representation of the
// SU(2) group.  The basic classes are PauliSpinor and PauliMatrix,
// which are 2-vectors and 2x2 matrices, respectively, of complex
// numbers.  The generators of the group are in the standard Pauli
// sigma matrix representation.  This package has particular members
// to facilitate a quantum mechanical calculation in which the Pauli
// spinor describes the spin-state of a fermion and the QM operators
// are described by Pauli matrices.  Pauli matrices are also used to
// describe mixed states, ensembles that contain mixtures of particles
// described by more than one Pauli spinor.
//
// The standard Pauli matrices are generated by invoking the construc-
// to with an argument of enum type EPauliIndex.  A EPauliIndex can be
//    kPauliOne,    kPauliSigma1,    kPauliSimga2,    kPauliSigma3.
// Any 2x2 matrix can be expressed as a sum over this basis.
//
// Spinors and matrices can be transformed under rotations according
// to the commutation rules for the SU(2) group.  Rotations may be
// specified either by Euler angles or by a rotation axis, or by
// supplying a member of the TThreeRotation class defined in
// TFourVector.h.  All angles are assumed to be in radians.
//
// This package depends on the ROOT framework (http://root.cern.ch).
//
// author: richard.t.jones at uconn.edu
// version: january 1, 2000
